name: Machine Learning CI Workflow

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  train-and-evaluate:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository Code
      uses: actions/checkout@v4

    - name: Set up Python 3.12.7
      uses: actions/setup-python@v5
      with:
        python-version: '3.12.7'

    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install mlflow==2.19.0 scikit-learn pandas numpy matplotlib seaborn

    - name: Run MLflow Project Experiment
      run: |
        cd MLProject
        mlflow run . --entry-point main

    - name: Upload Training Artifacts to GitHub
      if: always()
      uses: actions/upload-artifact@v4
      with:
        name: mlflow-local-results
        path: MLProject/mlruns/
